# Generated by Django 4.2.5 on 2023-10-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="school_info.group",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="groups",
            field=models.ManyToManyField(
                related_name="teachers", to="school_info.group"
            ),
        ),
    ]
